version = "3.10.1"

runner.dialect = scala213

maxColumn = 100

align.preset = some

danglingParentheses.preset = true

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

trailingCommas = always

spaces.inImportCurlyBraces = true
